server:
  port: 9000

spring:
  application:
    name: dcs-test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:13306/test?useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456

mybatis-plus:
  type-handlers-package: com.dgp.mybatis.typehandler.JsonObjToStringTypeHandler;com.dgp.test.typehandler.ListStringToStringTypeHandler

es:
  url: http://127.0.0.1:9200
  packages: com.dgp.test.esmapper
  dslPath: classpath:esmapper/*.dsl.xml

kafka:
  enable: true
  consumer:
    bootstrapServers: localhost:9092
    groupId: dpg-test-group
    topicList:
      - 'APP_LOG'
  producer:
    bootstrapServers: localhost:9092

redis:
  url: redis://127.0.0.1:16379
  password: redis
  mode: single
  database: 1
  redisson:
    enabled: true

xxl:
  job:
    sdk:
      adminUrl: https://xxljobdev.guokang.com
      userName: admin
      password: 123456
      appname: dgp-test
      address: http://10.10.6.192:7001
